/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "TTG_constants.h"

namespace TTG {

const TTGConstants g_TTG_constants;

TTGConstants::TTGConstants() {
}

} // namespace

