/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef TTG_CONSTANTS_H
#define TTG_CONSTANTS_H

#include "TTG_types.h"

namespace TTG {

class TTGConstants {
 public:
  TTGConstants();

};

extern const TTGConstants g_TTG_constants;

} // namespace

#endif
